fix: :bug: Fix parse syntax order.
miniRT-jiphyeonjeon/MiniRT pull request #87
Opened 2022-04-13 13:47 UTC by loiipa

**rt파일에 대한 파싱 순서 수정.**

**Mandatory** 기준 파싱
```
[x,y,z point] [braghness ratio] [normalized vector] [diameter] [height] [FOV] [RGB]

A	[bright ratio]	[RGB]
C	[x,y,z point]	[normalized vector]	[FOV]
L	[x,y,z point]	[braghness ratio]	[RGB]
sp	[x,y,z point]	[diameter]		[RGB]
pl	[x,y,z point]	[normalized vector]	[RGB]
cy	[x,y,z point]	[normalized vector]	[diameter]	[height]	[RGB]
co	[x,y,z point]	[normalized vector]	[diameter]	[height]	[RGB]
```

**Bonus** 기준 파싱
```
[x,y,z point] [braghness ratio] [normalized vector] [diameter] [height] [FOV] [texture info] [object spec]

A	[bright ratio]	[RGB]
C	[x,y,z point]	[normalized vector]	[FOV]
L	[x,y,z point]	[braghness ratio]	[RGB]
sp	[x,y,z point]	[diameter]		[texture info]	[object spec]
pl	[x,y,z point]	[normalized vector]	[texture info]	[object spec]
cy	[x,y,z point]	[normalized vector]	[diameter]	[height]	[texture info]	[object spec]
co	[x,y,z point]	[normalized vector]	[diameter]	[height]	[texture info]	[object spec]
```

추가된 부분의 문법
```
[texture info]
rgb [color1]
ck [color1] [color2] [width] [height]
bm [texture file] [bumpmap file]

[object spec]
[kd] [ks] [ksn]
```

이전 Bonus_object parse
```
sp	... [RGB]	[object spec]	[texture info]
pl	... [RGB]	[object spec]	[texture info]
cy	... [RGB] 	[object spec]	[texture info]
co	... [RGB] 	[object spec]	[texture info]
```

- closes #85

2022-04-13 13:48 UTC, loiipa commented on src_bonus/parse/parse_bool_bonus.c
> +			return (TRUE);
object일 때 [texture info]에 대한 문자 parse지점입니다.

2022-04-13 13:51 UTC, loiipa commented on src_bonus/scene/objects_bonus.c
> +		l->color.color = vec_get(p->rgb, 0, 255);
bumpmap일 때 color 값을 정의하지 않기 때문에, color를 bm이외의 해당 분기문 안에 각각 넣어 정의내리는 부분입ㄴ.다.

2022-04-13 13:57 UTC, loiipa commented on include_bonus/structure_bonus.h
> +	NOTCOLOR = -1,
color_type에서 유효하지 않은 인자값에서 예외처리를 위해 추가함.

2022-04-14 03:26 UTC, Hyoj-Kim commented on src_bonus/parse/parse_bool_bonus.c
> +			return (TRUE);
이 부분도 아래에서 strcmp를 한 번 하니까, enum값 이용해서 비교할 수 있지 않을까요...?

2022-04-14 03:30 UTC, Hyoj-Kim approved these changes
순서 바꾸면서 코드고치시느라 정말 고생많으셨습니다!
중간에 댓글 남긴대로, ft_strcmp가 두 번 사용되고 있는 부분만 한 번 더 고려해주시면 감사하겠습니다ㅎㅎ

2022-04-14 04:36 UTC, loiipa commented on src_bonus/parse/parse_bool_bonus.c
> +			return (TRUE);
위 함수의 리턴값을 enum으로 이용해서 color_type_get과 기능을 합치면 가능할 것 같습니다.

2022-04-14 04:39 UTC, loiipa commented on src_bonus/parse/parse_bool_bonus.c
> +			return (TRUE);
의도 자체는 유효성 검사 -> 값 정의라는 두단계로 생각을 해서 두번 썼었습니다.

2022-04-14 05:21 UTC, Hyoj-Kim requested changes
ft_strcmp 수정해주세요!

2022-04-14 05:26 UTC, loiipa commented on src_bonus/parse/parse_str_set_bonus.c
> +
valid, get함수에서 각각 ft_strcmp 쓰던걸 함수 하나로 합쳐서 한번만 쓰게 했습니다.

2022-04-14 05:27 UTC, loiipa commented on src_bonus/parse/parse_str_set_bonus.c
> +	idx++;
이미 color_id는 get함수에 의해 정의되었기 때문에 index를 하나 넘깁니다.

2022-04-14 05:31 UTC, Hyoj-Kim approved these changes
검사랑 return까지 한 번에 하니까 두 번 작업하지 않아도 되겠군요!! 고생하셨습니당ㅎㅎ

2022-04-14 05:31 UTC, merged